### ISSUE TITLE
Add sorting in requires/imports rule

### ISSUE THREAD

**Issue by diogotorres97** [uphold/eslint-config-uphold#41]
https://www.npmjs.com/package/eslint-plugin-require-sort

**Comment by satazor** [comment]
https://www.npmjs.com/package/eslint-plugin-import works pretty well and is well maintained. Worth checking out.

Also see example usage: https://github.com/moxystudio/eslint-config/blob/4cd2555e7727eaca66aa271915c282217f31a4eb/packages/eslint-config-base/lib/rules/import.js

**Comment by Americas** [comment]
@satazor that's all well and good, we can look to change the one we already use for import/export lines. But what we need is a sort rule for require lines. Maybe I didn't dive deep enough, but it doesn't seem to support that.

**Comment by satazor** [comment]
> But what we need is a sort rule for require lines

If you mean require statements at the top of files, yes this plugin supports it. Check these test sample files:

- https://github.com/moxystudio/eslint-config/blob/4cd2555e7727eaca66aa271915c282217f31a4eb/packages/eslint-config-base/test/samples/es2015-cjs/contrived.good.js#L5 (good ordering, per our sorting standard)
- https://github.com/moxystudio/eslint-config/blob/4cd2555e7727eaca66aa271915c282217f31a4eb/packages/eslint-config-base/test/samples/es2015-cjs/contrived.bad.js (bad ordering, per our sorting standard)

At the moment the plugin does not auto-fix ordering. There was a discussion about it here https://github.com/import-js/eslint-plugin-import/issues/2154 but the maintainer seems to disagree supporting it. However, having linting errors right when you are coding in your editor is pretty good and sufficient.

Let me know if I'm misunderstanding what you mean.

**Comment by Americas** [comment]
Alright then! :smile: 

But there doesn't seem to have an option to group just destructured requires, I think that is a dealbreaker.

The biggest problem here is that senior management has no time for simple things like these, but insist on making the decisions :shrug: so nothing changes :cry:

**Comment by satazor** [comment]
> But there doesn't seem to exist an option to group just destructured requires, I think that is a dealbreaker.

You want top put together destructured requires within the same group (e.g.: within nodejs native requires)? I think that's going to far, do we really need that for code to become more readable? We always should ask this ourselves so that our personal preference weights less.

> The biggest problem here is that senior management has no time for simple things like these, but insist on making the decisions 🤷 so nothing changes 😢

@nunofgs perhaps the RFC process could help here? It would contain guidelines on how the RFC should / could be approved or declined.

**Comment by Americas** [comment]
I'm not saying it's a dealbreaker to me :smile: I'm happy to abide by any guideline if that means less work during coding, and less hassle when reviewing! If on top of that the code is more readable, great!

**Comment by waldyrious** [comment]
Should this issue be considered resolved now that #53 has been merged?

**Comment by satazor** [comment]
Yes we can close this. Thanks for pointing it out @waldyrious
